### ISSUE TITLE
Some feedback on default behavior: yarn clean, install on restore, and bundling

### ISSUE THREAD

**Issue by johlrich** [natemcmaster/Yarn.MSBuild#1]
We're having a discussion within fable on whether or not to embed yarn and I came across this package. Here is an excerpt of a comment I made on that issue wrt how the msbuild targets work after trying it out. 

> * The nuget package for that bundles a version of yarn with it, so it works without yarn installed.
>    * I wondered if it made more sense for the msbuild task to try and use path first and if not, then fallback to dist.
> * The package currently calls yarn install on dotnet build. I think this would make more sense being on dotnet restore like paket does.
> * The package currently calls yarn clean when dotnet clean is called. This doesn't seem right considering that dotnet clean is intended to clean build artifacts and yarn clean seems to be dealing with cleaning out unneeded files in your node_modules folder, not build artifacts. It also creates a .yarnclean file when you run it, which may confuse users. https://yarnpkg.com/lang/en/docs/cli/clean/

If interested, you can see the full conversation at https://github.com/fable-compiler/Fable/issues/925

**Comment by natemcmaster** [comment]
> The nuget package for that bundles a version of yarn with it

Would it be helpful to have a version that doesn't bundle yarn, just the MSBuild targets/tasks?

> The package currently calls yarn install on dotnet build. 

I totally agree it would be ideal to run `yarn install` as a post NuGet restore step, however, I'm not sure how to implement that in a way that doesn't require calling dotnet-restore twice. The lifecycle of NuGet restore is such that a PackageReference can't add a post-restore hook until after restore has run once. This means for `yarn install` to execute, you would have to run 

1. dotnet restore - downloads Yarn.MSBuild and adds a the post restore-hook
2. dotnet restore - runs `yarn install`

> The package currently calls yarn clean when dotnet clean is called

Good feedback. I looked at this more and agree we should remove that.

**Comment by natemcmaster** [comment]
I took a closer look at `yarn clean` and agree that in most cases we don't really want to call it when `dotnet clean` is executed. I've pushed a new version that removes the call to `yarn clean`.

Also, I've decided to keep yarn bundled in the nupkg. This utility is light enough that those who want to use a globally installed version of yarn can probably just invoke an Exec task. (`<Exec Command="yarn install" />`. 

I'm going to leave this issue open as the last piece of feedback - about running install along with restore - is something I'd like to address, but can't until NuGet makes it possible for a PackageReference to easily chain of the restore target.

**Comment by natemcmaster** [comment]
Tracking: https://github.com/NuGet/Home/issues/4781 for support from NuGet for a restore callback in projects.

**Comment by natemcmaster** [comment]
So, NuGet released an update that in theory makes it possible to chain into restore. However, this is restricted from packages. A package cannot affect the outcome of a restore. Basically, you have to write the dotnet-restore integration yourself. As far as I can tell, the only way to make Visual Studio run `yarn install` along with dotnet-restore is to write a Visual Studio extension that chains into the restore hook.

I'm going to remove the automatic execution of `yarn install` in the 1.2.0 version of this package since it doesn't belong in `/target:Build`. I've updated the README with new instructions on how to use this.
