### ISSUE TITLE
Possible mistake in YarnWorkingDir property condition 

### ISSUE THREAD

**Issue by jelical** [natemcmaster/Yarn.MSBuild#11]
`<YarnWorkingDir Condition=" '$(YarnWorkingDir)' != '' ">$(MSBuildProjectDirectory)</YarnWorkingDir>`

I believe, your intentions were opposite:
` Condition=" '$(YarnWorkingDir)' == '' "`

**Comment by natemcmaster** [comment]
Oops, yeah. Can you send a PR to fix it?

**Comment by jelical** [comment]
#12 
Enjoy

**Comment by natemcmaster** [comment]
This fix is in 1.5.2. It may take up to an hour for nuget.org to finish indexing this package https://www.nuget.org/packages/Yarn.MSBuild/1.5.2 Thanks again for contributing.
