### ISSUE TITLE
YarnMSBuild run yarn even if I didn't change anything in js

### ISSUE THREAD

**Issue by Kurunova** [natemcmaster/Yarn.MSBuild#18]
Good day, Nate. 
When I build solution with YarnMSBuild it makes more time then usually. Could YarnMSBuild track changes in js and build yarn only if something changes in scripts?

**Comment by natemcmaster** [comment]
MSbuild already has a solution for this problem. See https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-incrementally. It requires you specify the filepaths of all inputs to your yarn command and the exact outputs. I don't think this is a problem I can solve generically for everyone who uses this library.

**Comment by Kurunova** [comment]
Thank you, Nate.
