### ISSUE TITLE
Global Node.js dependency

### ISSUE THREAD

**Issue by cgravill** [natemcmaster/Yarn.MSBuild#3]
Thanks for making this tool, I've found it useful locally.

I'd like to use it on build agents where we don't have a globally installed Node.js. This is to ensure reproducible builds and make it easier to configure agents. There's a NuGet for Node.js which is current https://www.nuget.org/packages/Node.js.redist/

I experimented in a few ways but couldn't see a clean way to provide this instance of node.exe i.e. copying it in, calling yarn.js directory, or sticking it the ExecutablePath as a prefix. Do you have a suggested approach for this?

**Comment by natemcmaster** [comment]
When you're using Node.js.redist, how are you installing it and using it? Do your scripts or MSbuild targets know where the node executable is on disk? If so, you should be able to prepend this location to the PATH environment variable. This is required because the bootstrapper script from the yarn redist looks like this:

```cmd
@echo off
node "%~dp0\yarn.js" %*
```
and linux/macos:
```sh
#!/bin/sh
argv0=$(echo "$0" | sed -e 's,\\,/,g')
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")

case "$(uname -s)" in
  Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

command_exists() {
  command -v "$1" >/dev/null 2>&1;
}

if command_exists node; then
  if [ "$YARN_FORCE_WINPTY" = 1 ]; then
    winpty node "$basedir/yarn.js" "$@"
  else
    exec node "$basedir/yarn.js" "$@"
  fi
  ret=$?
# Debian and Ubuntu use "nodejs" as the name of the binary, not "node", so we
# search for that too. See:
# https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907
elif command_exists nodejs; then
  exec nodejs "$basedir/yarn.js" "$@"
  ret=$?
else
  echo 'Yarn requires Node.js 4.0 or higher to be installed.'
  ret=1
fi

exit $ret
```

**Comment by cgravill** [comment]
We're installing Node.js.redist via Paket and yes it's at a known location so can call it without issue. If I were directly calling an exec I could do something like this http://blog.jdhardy.ca/2011/12/setting-environment-variables-for.html but I can't see how to achieve this effect without modifying the Yarn.MSBuild.targets file directly.

**Comment by natemcmaster** [comment]
What if I added support for a new property like this?

Your csproj/msbuild code:
```xml
<PropertyGroup>
   <NodeJSExecutablePath>C:\where\node.exe</NodeJSExecutablePath>
</PropertyGroup>
```
This could also be set via command line
```
dotnet build -p:NodeJSExecutablePath=/usr/local/bin/nodejs
```

**Comment by cgravill** [comment]
Yes that looks very promising, thanks! I'm equally happy if it's the directory to node as well.

If the path can be relative to one of the Yarn.MSBuild files that would be ideal. An absolute path is doable too.

**Comment by natemcmaster** [comment]
@cgravill I added NodeJSExecutablePath to the task in https://github.com/natemcmaster/Yarn.MSBuild/commit/a66a3029cf4da688223cb1a0555f87f8dc8ae879. Can you give this build a try to make sure it works for you?

https://www.myget.org/feed/natemcmaster/package/nuget/Yarn.MSBuild/1.0.2-build.69+master

If it does, I'll push 1.0.2 to nuget.org soon.

**Comment by natemcmaster** [comment]
I did some testing and this seemed to work for me. I pushed 1.0.2 to nuget.org. Let me know if you have issues and we can reopen.

Closed as fixed in https://www.nuget.org/packages/Yarn.MSBuild/1.0.2

**Comment by cgravill** [comment]
Thanks this works great!

I'm now able to chain NuGet fetch of dependencies and run Yarn automatically in a reliable way, even on clean build agents. In case it's useful to others, this is how I configured my project files:

```xml
<PropertyGroup
  <NodeJsExecutablePath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\packages\Node.js.redist\tools\win-x64\node.exe'))</NodeJsExecutablePath>
</PropertyGroup>
<Import Project="..\..\packages\Yarn.MSBuild\build\Yarn.MSBuild.targets" Condition="Exists('..\..\packages\Yarn.MSBuild\build\Yarn.MSBuild.targets')" Label="Paket" />
```
