### ISSUE TITLE
Warning when using `dotnet restore` use `.shproj` ?

### ISSUE THREAD

**Issue by Socolin** [natemcmaster/Yarn.MSBuild#35]
Hello,

When using this I got a warning at build

```
.... warning NU1503: Skipping restore for project .... . The project file may be invalid or missing targets required for restore. [C:\dev\git\mediaclip-hub\Mediaclip.Hub.sln]
```

After some search I found that instead of using a `.csproj`, we can use `.shproj` and then this warning disable since the project will not be in the list of project to restore: https://github.com/NuGet/NuGet.Client/blob/b0fef98e6328948e7669297d6869fa792b39e805/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L269

I don't know if this change imply any unexpected change but maybe the documentation could mention it in the README  ?

**Comment by natemcmaster** [comment]
Feel free to propose a documentation update, though, I don't think shproj is a very commonly used feature.
