### ISSUE TITLE
Add new package or option for Yarn v2

### ISSUE THREAD

**Issue by BrennanConroy** [natemcmaster/Yarn.MSBuild#36]
**Is your feature request related to a problem? Please describe.**
Yarn v2 has improved reliability when installing packages (my main want)

**Describe the solution you'd like**
Since Yarn v2 is a breaking change, it's probably not a good idea to just change the version in this package.

Two solutions I see:
* have a v2 of this package for Yarn v2
* have an option to choose which Yarn version is used and default to Yarn v1 to not break anyone

**Describe alternatives you've considered**
N/A

**Additional context**
Migration guide for moving from Yarn v1 to v2
https://yarnpkg.com/getting-started/migration

**Comment by natemcmaster** [comment]
So far, the nuget package version has aligned with the yarn version it redistributes. I'd like to keep that approach unless there is a compelling reason to make a new package ID altogether.
