### ISSUE TITLE
Question about "webpack serve"

### ISSUE THREAD

**Issue by nthNathan** [natemcmaster/Yarn.MSBuild#42]
The command "run webpack" is working great for me, but when I try "run webpack serve" (or "run webpack --watch") it doesn't continue with the rest of the build.

I am guessing that is because "run webpack serve" starts a process that doesn't finish (it just starts up the webpack server and doesn't exit the command line), and that blocks the rest of the build.

So I think one possible approach would be to run the yarn command as a non-blocking background process, but I don't know if such a thing is possible or supported.

I'm interested if anyone has run into this issue, or if anyone knows a good approach to using webpack dev-server with Yarn.MSBuild. It seems like a very common use-case.

**Comment by natemcmaster** [comment]
I don't think this is something we could feasibly build. Non-blocking background processes are not supported from MSBuild tasks, as far as I know. I would recommend using webpack normally instead of trying to invoke it from MSBuild.
