### ISSUE TITLE
Package provided yarn not available to webpack commands

### ISSUE THREAD

**Issue by mungojam** [natemcmaster/Yarn.MSBuild#9]
Not sure if this would fit well in this package or not. I am finding that my webpack sub-tasks that need to call yarn can't make use of the package-provided version of yarn because it isn't on the path even when I invoke the top level task using Yarn.MsBuild.

I am using Yarn.MSBuild to first call `yarn install` and then to call `yarn run build` which invokes a webpack task in package.json (I think it's webpack, I'm using the new asp.net SPA template). 

It works fine if I have yarn installed, but I'd rather not have that as a dependency. Maybe the better thing is to add yarn as a npm devDependency which I've just tested and works fine.

Feel free to close this if you don't think it's appropriate for Yarn.MsBuild to make this work.

I vaguely wondered if: https://github.com/yarnpkg/yarn/commit/3a04db792a0ba7cdef928e8ff52ecf0d4430829a would make it work automatically but I don't know what CWD is used for in yarn.

**Comment by natemcmaster** [comment]
Help me make sure I understand the problem correctly. Are you invoking webpack via the `<Yarn>` task? Inside the task, we could easily prepending the PATH environment variable with the directory containing the bundled yarn executables, before invoking the new process. Would that solve your problem?

**Comment by mungojam** [comment]
That's right yeah, and adding to the PATH should fix it. 

So I have:

```
<Yarn Command="install" WorkingDirectory="$(YarnWorkingDir)" />
<Yarn Command="run build" WorkingDirectory="$(YarnWorkingDir)" />
```

And in my package.json:

```
  "scripts": {
    "build": "yarn run clean && react-scripts build && yarn run build-rename"
  # etc.
}
```

The `install` call works fine, but the `run build` doesn't unless I add a devDependency to yarn.

**Comment by natemcmaster** [comment]
Just uploaded 1.5.1. Let me know if it works.

https://www.nuget.org/packages/Yarn.MSBuild/1.5.1

**Comment by mungojam** [comment]
Thanks, that has worked
